### ISSUE TITLE
Compile bug: error: no matching function for call to 'hipStreamWaitEvent'

### ISSUE THREAD

**Issue by wtarreau** [iacopPBK/llama.cpp-gfx906#10]
### Git commit

$ git rev-parse HEAD
821591ab317f092be573aeba17e202820db5789d

### Operating systems

Linux

### GGML backends

HIP

### Problem description & steps to reproduce

I'm building with ./SCRIPT_compile_MI50.sh.

Since the recent merge of upstream, I'm getting this error when building on Ubuntu-24.04.3:
```
/home/willy/llama.cpp-gfx906/ggml/src/ggml-cuda/ggml-cuda.cu:3249:28: error: no matching function for call to 'hipStreamWaitEvent'
 3249 |                 CUDA_CHECK(cudaStreamWaitEvent(stream, concurrent_event->fork_event));
      |                            ^~~~~~~~~~~~~~~~~~~
/home/willy/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/vendors/hip.h:112:29: note: expanded from macro 'cudaStreamWaitEvent'
  112 | #define cudaStreamWaitEvent hipStreamWaitEvent
      |                             ^~~~~~~~~~~~~~~~~~
/home/willy/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/common.cuh:159:40: note: expanded from macro 'CUDA_CHECK'
  159 | #define CUDA_CHECK(err) CUDA_CHECK_GEN(err, cudaSuccess, cudaGetErrorString)
      |                                        ^~~
/home/willy/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/common.cuh:153:22: note: expanded from macro 'CUDA_CHECK_GEN'
  153 |         auto err_ = (err);                                                          \
      |                      ^~~
```
Grepping for this function, I'm seeing that one argument is missing at two call places:
```
ggml/src/ggml-cuda/ggml-cuda.cu:                CUDA_CHECK(cudaStreamWaitEvent(stream, src0_extra->events[ctx.device][0], 0));
ggml/src/ggml-cuda/ggml-cuda.cu:                CUDA_CHECK(cudaStreamWaitEvent(ctx.stream(), src0_extra->events[id][is], 0));
ggml/src/ggml-cuda/ggml-cuda.cu:        CUDA_CHECK(cudaStreamWaitEvent(cuda_ctx_dst->stream(), cuda_ctx_src->copy_event, 0));
ggml/src/ggml-cuda/ggml-cuda.cu:                CUDA_CHECK(cudaStreamWaitEvent(stream, concurrent_event->fork_event));
ggml/src/ggml-cuda/ggml-cuda.cu:                            CUDA_CHECK(cudaStreamWaitEvent(cuda_ctx->stream(), concurrent_event->join_events[i - 1]));
ggml/src/ggml-cuda/ggml-cuda.cu:        CUDA_CHECK(cudaStreamWaitEvent(cuda_ctx->stream(), (cudaEvent_t)event->context, 0));
```
I tried to append `, 0` to these two locations but then it failed futher:
```
[ 35%] Linking HIP shared library ../../../bin/libggml-hip.so
ld.lld: error: duplicate symbol: __float2bfloat16(float)
>>> defined at acc.cu
>>>            CMakeFiles/ggml-hip.dir/__/ggml-cuda/acc.cu.o:(__float2bfloat16(float))
>>> defined at add-id.cu
>>>            CMakeFiles/ggml-hip.dir/__/ggml-cuda/add-id.cu.o:(.text+0x0)

ld.lld: error: duplicate symbol: __bfloat1622float2(__hip_bfloat162)
>>> defined at acc.cu
>>>            CMakeFiles/ggml-hip.dir/__/ggml-cuda/acc.cu.o:(__bfloat1622float2(__hip_bfloat162))
>>> defined at add-id.cu
>>>            CMakeFiles/ggml-hip.dir/__/ggml-cuda/add-id.cu.o:(.text+0x40)
(...)
```

I'm not pasting it all there since I don't know if it's a side effect of my attempt at fixing the other one.

Note that I had already faced this issue with upstream llama.cpp when building for gfx906 but the previous build script from -gfx906 addressed it, and I spent quite a bit of time trying to isolate the relevant build options that affect the build without finding them yet. It's just that now it's generalized and touched the -gfx906 fork as well.

I'm on ROCm-6.4.4 from AMD by the way, since previous 7.0.1 + tensile files used to cause dirty crashes with certain models.

### First Bad Commit

Uncertain yet but at least 4206a6000 did work fine (tag b6905).

### Compile command

```shell
./SCRIPT_compile_MI50.sh
```

### Relevant log output

```shell
/home/willy/llama.cpp-gfx906/ggml/src/ggml-cuda/ggml-cuda.cu:3249:28: error: no matching function for call to 'hipStreamWaitEvent'
 3249 |                 CUDA_CHECK(cudaStreamWaitEvent(stream, concurrent_event->fork_event));
      |                            ^~~~~~~~~~~~~~~~~~~
/home/willy/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/vendors/hip.h:112:29: note: expanded from macro 'cudaStreamWaitEvent'
  112 | #define cudaStreamWaitEvent hipStreamWaitEvent
      |                             ^~~~~~~~~~~~~~~~~~
/home/willy/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/common.cuh:159:40: note: expanded from macro 'CUDA_CHECK'
  159 | #define CUDA_CHECK(err) CUDA_CHECK_GEN(err, cudaSuccess, cudaGetErrorString)
      |                                        ^~~
/home/willy/llama.cpp-gfx906/ggml/src/ggml-hip/../ggml-cuda/common.cuh:153:22: note: expanded from macro 'CUDA_CHECK_GEN'
  153 |         auto err_ = (err);                                                          \
      |                      ^~~
```
